# Generated by Django 2.2.1 on 2019-06-20 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iirssurveyapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userloclayer',
            name='layer',
        ),
    ]
