# Generated by Django 2.2.1 on 2019-06-24 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iirssurveyapp', '0002_remove_userloclayer_layer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Layers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layer', models.CharField(max_length=50)),
            ],
        ),
    ]
