# Generated by Django 2.2.1 on 2019-06-24 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iirssurveyapp', '0003_layers'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Layers',
            new_name='Layer',
        ),
    ]
